#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#

# show git environment
echo Running $BASH_SOURCE
set | egrep GIT
echo PWD is $PWD

# stop on error
set -e

flake8 bmeg_app/

