version: '3'
services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.9.1
    container_name: odfe-elastic
    environment:
      - cluster.name=odfe-cluster
      - node.name=elastic
      - discovery.type=single-node
    #   - cluster.initial_master_nodes=elastic,odfe-node2
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the Elasticsearch user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
      - odfe-data1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9600:9600 # required for Performance Analyzer
    networks:
      - odfe-net

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:7.9.1  
    container_name: odfe-kibana
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      ELASTICSEARCH_URL: http://elastic:9200
      ELASTICSEARCH_HOSTS: http://elastic:9200
    networks:
      - odfe-net

  app:
    build: ./app
    container_name: odfe-app
    volumes: 
    - ./app:/app  
    ports:
      - 8050:8050
    expose:
      - "8050"
    environment:
      ELASTICSEARCH_URL: http://elastic:9200
      ELASTICSEARCH_HOSTS: http://elastic:9200
    networks:
      - odfe-net

volumes:
  odfe-data1:
  odfe-data2:

networks:
  odfe-net: