bmeg:
    credentials: ./bmeg_credentials.json
    graph: rc5
    url: https://bmeg.io/grip

DEV:
    host: 0.0.0.0
    port: 8050
    dev: True
    basepath: app

PROD:
    host: 0.0.0.0
    port: 8050
    dev: False
    basepath: app
